/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as OperationalStateRouteImport } from './routes/operational-state'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as IndexRouteImport } from './routes/index'

const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationalStateRoute = OperationalStateRouteImport.update({
  id: '/operational-state',
  path: '/operational-state',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/incidents': typeof IncidentsRoute
  '/metrics': typeof MetricsRoute
  '/operational-state': typeof OperationalStateRoute
  '/recommendations': typeof RecommendationsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/incidents': typeof IncidentsRoute
  '/metrics': typeof MetricsRoute
  '/operational-state': typeof OperationalStateRoute
  '/recommendations': typeof RecommendationsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/incidents': typeof IncidentsRoute
  '/metrics': typeof MetricsRoute
  '/operational-state': typeof OperationalStateRoute
  '/recommendations': typeof RecommendationsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/incidents' | '/metrics' | '/operational-state' | '/recommendations'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/incidents' | '/metrics' | '/operational-state' | '/recommendations'
  id:
    | '__root__'
    | '/'
    | '/incidents'
    | '/metrics'
    | '/operational-state'
    | '/recommendations'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IncidentsRoute: typeof IncidentsRoute
  MetricsRoute: typeof MetricsRoute
  OperationalStateRoute: typeof OperationalStateRoute
  RecommendationsRoute: typeof RecommendationsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operational-state': {
      id: '/operational-state'
      path: '/operational-state'
      fullPath: '/operational-state'
      preLoaderRoute: typeof OperationalStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IncidentsRoute: IncidentsRoute,
  MetricsRoute: MetricsRoute,
  OperationalStateRoute: OperationalStateRoute,
  RecommendationsRoute: RecommendationsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
