/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteersRouteImport } from './routes/volunteers'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as OperationalStateRouteImport } from './routes/operational-state'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NavigationRouteImport } from './routes/navigation'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as IncidentsRouteImport } from './routes/incidents'
import { Route as ExecutiveSituationRoomRouteImport } from './routes/executive-situation-room'
import { Route as CrowdIntelligenceRouteImport } from './routes/crowd-intelligence'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const VolunteersRoute = VolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationalStateRoute = OperationalStateRouteImport.update({
  id: '/operational-state',
  path: '/operational-state',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigationRoute = NavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsRoute = IncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveSituationRoomRoute = ExecutiveSituationRoomRouteImport.update({
  id: '/executive-situation-room',
  path: '/executive-situation-room',
  getParentRoute: () => rootRouteImport,
} as any)
const CrowdIntelligenceRoute = CrowdIntelligenceRouteImport.update({
  id: '/crowd-intelligence',
  path: '/crowd-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/copilot': typeof CopilotRoute
  '/crowd-intelligence': typeof CrowdIntelligenceRoute
  '/executive-situation-room': typeof ExecutiveSituationRoomRoute
  '/incidents': typeof IncidentsRoute
  '/metrics': typeof MetricsRoute
  '/navigation': typeof NavigationRoute
  '/notifications': typeof NotificationsRoute
  '/operational-state': typeof OperationalStateRoute
  '/recommendations': typeof RecommendationsRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/volunteers': typeof VolunteersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/copilot': typeof CopilotRoute
  '/crowd-intelligence': typeof CrowdIntelligenceRoute
  '/executive-situation-room': typeof ExecutiveSituationRoomRoute
  '/incidents': typeof IncidentsRoute
  '/metrics': typeof MetricsRoute
  '/navigation': typeof NavigationRoute
  '/notifications': typeof NotificationsRoute
  '/operational-state': typeof OperationalStateRoute
  '/recommendations': typeof RecommendationsRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/volunteers': typeof VolunteersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/copilot': typeof CopilotRoute
  '/crowd-intelligence': typeof CrowdIntelligenceRoute
  '/executive-situation-room': typeof ExecutiveSituationRoomRoute
  '/incidents': typeof IncidentsRoute
  '/metrics': typeof MetricsRoute
  '/navigation': typeof NavigationRoute
  '/notifications': typeof NotificationsRoute
  '/operational-state': typeof OperationalStateRoute
  '/recommendations': typeof RecommendationsRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
  '/volunteers': typeof VolunteersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/copilot'
    | '/crowd-intelligence'
    | '/executive-situation-room'
    | '/incidents'
    | '/metrics'
    | '/navigation'
    | '/notifications'
    | '/operational-state'
    | '/recommendations'
    | '/settings'
    | '/timeline'
    | '/volunteers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/copilot'
    | '/crowd-intelligence'
    | '/executive-situation-room'
    | '/incidents'
    | '/metrics'
    | '/navigation'
    | '/notifications'
    | '/operational-state'
    | '/recommendations'
    | '/settings'
    | '/timeline'
    | '/volunteers'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/copilot'
    | '/crowd-intelligence'
    | '/executive-situation-room'
    | '/incidents'
    | '/metrics'
    | '/navigation'
    | '/notifications'
    | '/operational-state'
    | '/recommendations'
    | '/settings'
    | '/timeline'
    | '/volunteers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CopilotRoute: typeof CopilotRoute
  CrowdIntelligenceRoute: typeof CrowdIntelligenceRoute
  ExecutiveSituationRoomRoute: typeof ExecutiveSituationRoomRoute
  IncidentsRoute: typeof IncidentsRoute
  MetricsRoute: typeof MetricsRoute
  NavigationRoute: typeof NavigationRoute
  NotificationsRoute: typeof NotificationsRoute
  OperationalStateRoute: typeof OperationalStateRoute
  RecommendationsRoute: typeof RecommendationsRoute
  SettingsRoute: typeof SettingsRoute
  TimelineRoute: typeof TimelineRoute
  VolunteersRoute: typeof VolunteersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteers': {
      id: '/volunteers'
      path: '/volunteers'
      fullPath: '/volunteers'
      preLoaderRoute: typeof VolunteersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operational-state': {
      id: '/operational-state'
      path: '/operational-state'
      fullPath: '/operational-state'
      preLoaderRoute: typeof OperationalStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigation': {
      id: '/navigation'
      path: '/navigation'
      fullPath: '/navigation'
      preLoaderRoute: typeof NavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents': {
      id: '/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof IncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive-situation-room': {
      id: '/executive-situation-room'
      path: '/executive-situation-room'
      fullPath: '/executive-situation-room'
      preLoaderRoute: typeof ExecutiveSituationRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crowd-intelligence': {
      id: '/crowd-intelligence'
      path: '/crowd-intelligence'
      fullPath: '/crowd-intelligence'
      preLoaderRoute: typeof CrowdIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CopilotRoute: CopilotRoute,
  CrowdIntelligenceRoute: CrowdIntelligenceRoute,
  ExecutiveSituationRoomRoute: ExecutiveSituationRoomRoute,
  IncidentsRoute: IncidentsRoute,
  MetricsRoute: MetricsRoute,
  NavigationRoute: NavigationRoute,
  NotificationsRoute: NotificationsRoute,
  OperationalStateRoute: OperationalStateRoute,
  RecommendationsRoute: RecommendationsRoute,
  SettingsRoute: SettingsRoute,
  TimelineRoute: TimelineRoute,
  VolunteersRoute: VolunteersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
