import json
from typing import Any

from pydantic import BaseModel, Field

from app.intelligence import AIOrchestrator
from app.intelligence.prompts.base import BasePrompt, PromptMetadata, PromptVersion
from app.intelligence.structured_output import AIResponse


class AIRecommendationItem(BaseModel):
    """Represents a single logistical or safety recommendation generated by AI."""

    action_type: str = Field(..., description="The name/action of the recommendation (e.g. 'Reroute Volunteers to Ingress Gate 1').")
    priority: str = Field(..., description="Priority level of the recommendation: 'low', 'medium', 'high', 'critical'.")
    confidence: float = Field(..., description="Confidence score of this recommendation (0.0 to 1.0).")
    why: str = Field(..., description="Concise operator-facing description of why this recommendation is needed.")
    evidence: str = Field(..., description="Specific operational evidence supporting this action.")
    operational_data_used: list[str] = Field(..., description="Specific operational/telemetry data parameters utilized.")
    alternative_actions: list[str] = Field(..., description="List of alternative actions available to the operator.")
    trade_offs: str = Field(..., description="Operator-facing description of operational trade-offs for this recommendation.")
    explanation: str = Field(..., description="Human-readable explanation of the recommendation details.")
    estimated_impact: str = Field(..., description="Estimated operational impact (e.g. 'Reduce queue bottleneck by 25%').")
    estimated_recovery_time_minutes: int = Field(..., description="Estimated recovery time in minutes.")
    operational_reasoning: str = Field(..., description="Concise operational reasoning referencing telemetry parameters, active incidents, and operational state.")


class AIRecommendationGeneratorResponse(AIResponse):
    """Structured response containing AI generated stadium recommendations."""

    recommendations: list[AIRecommendationItem] = Field(..., description="List of generated recommendations.")


class AIRecommendationGeneratorPrompt(BasePrompt):
    """Prompt template for generating AI recommendations."""

    def __init__(self) -> None:
        metadata = PromptMetadata(
            name="ai_recommendation_generator",
            description="Generates dynamic logistical and safety recommendations using Gemini.",
            author="System",
            tags=["agent", "recommendation-generator"],
        )
        versions = [
            PromptVersion(
                version="v1",
                template=(
                    "You are the ATLAS Stadium Operations AI Recommendation Engine.\n"
                    "Analyze the current stadium conditions:\n"
                    "- Telemetry & Crowd Conditions: {telemetry}\n"
                    "- Active Incidents: {incidents}\n"
                    "- Operational State: {operational_state}\n\n"
                    "Based on these conditions, generate human-readable logistical, routing, safety, and volunteer allocation recommendations.\n"
                    "For every recommendation, you must include:\n"
                    "1. action_type, priority, confidence.\n"
                    "2. why: Concise operator-facing explanation of why it is needed.\n"
                    "3. evidence: The evidence supporting this action.\n"
                    "4. operational_data_used: Specific telemetry or event fields referenced (e.g. average_crowd_density, queue_waiting_minutes).\n"
                    "5. alternative_actions: Alternative responses the operator can select.\n"
                    "6. trade_offs: Operational trade-offs of executing this recommendation.\n"
                    "7. explanation, estimated_impact, estimated_recovery_time_minutes, operational_reasoning.\n\n"
                    "CRITICAL RULES:\n"
                    "- Never expose chain of thought (internal planning or reasoning steps) in any of the fields.\n"
                    "- Use concise, professional, operator-facing language appropriate for a mission control dashboard.\n"
                    "Format your response to match the requested structured schema.\n"
                )
            )
        ]
        super().__init__(metadata, versions)


class AIRecommendationGenerator:
    """AI Agent responsible for generating dynamic stadium recommendations."""

    def __init__(self, orchestrator: AIOrchestrator) -> None:
        self.orchestrator = orchestrator
        self.prompt_definition = AIRecommendationGeneratorPrompt()

        # Register prompt template in the registry
        latest_version = self.prompt_definition.get_version("latest")
        self.orchestrator.registry.register(
            name=self.prompt_definition.metadata.name,
            version=latest_version.version,
            template=latest_version.template,
            description=latest_version.description,
        )

    async def generate_recommendations(
        self,
        telemetry: dict[str, Any],
        incidents: list[dict[str, Any]],
        operational_state: dict[str, Any],
    ) -> AIRecommendationGeneratorResponse:
        """Calls the AI Orchestrator to generate structured recommendations using Gemini."""
        return await self.orchestrator.execute(
            prompt_name=self.prompt_definition.metadata.name,
            prompt_version="latest",
            context_zone_id=None,
            schema=AIRecommendationGeneratorResponse,
            telemetry=json.dumps(telemetry, default=str),
            incidents=json.dumps(incidents, default=str),
            operational_state=json.dumps(operational_state, default=str),
            min_confidence=0.0,
        )
