import json
from typing import Any, List

from pydantic import BaseModel, Field

from app.intelligence import AIOrchestrator
from app.intelligence.prompts.base import BasePrompt, PromptMetadata, PromptVersion
from app.intelligence.structured_output import AIResponse


class AIRecommendationItem(BaseModel):
    """Represents a single logistical or safety recommendation generated by AI."""

    action_type: str = Field(..., description="The name/action of the recommendation (e.g. 'Reroute Volunteers to Ingress Gate 1').")
    priority: str = Field(..., description="Priority level of the recommendation: 'low', 'medium', 'high', 'critical'.")
    confidence: float = Field(..., description="Confidence score of this recommendation (0.0 to 1.0).")
    explanation: str = Field(..., description="Human-readable explanation of the recommendation details.")
    estimated_impact: str = Field(..., description="Estimated operational impact (e.g. 'Reduce queue bottleneck by 25%').")
    estimated_recovery_time_minutes: int = Field(..., description="Estimated recovery time in minutes.")
    operational_reasoning: str = Field(..., description="Concise operational reasoning referencing telemetry parameters, active incidents, and operational state.")


class AIRecommendationGeneratorResponse(AIResponse):
    """Structured response containing AI generated stadium recommendations."""

    recommendations: List[AIRecommendationItem] = Field(..., description="List of generated recommendations.")


class AIRecommendationGeneratorPrompt(BasePrompt):
    """Prompt template for generating AI recommendations."""

    def __init__(self) -> None:
        metadata = PromptMetadata(
            name="ai_recommendation_generator",
            description="Generates dynamic logistical and safety recommendations using Gemini.",
            author="System",
            tags=["agent", "recommendation-generator"],
        )
        versions = [
            PromptVersion(
                version="v1",
                template=(
                    "You are the ATLAS Stadium Operations AI Recommendation Engine.\n"
                    "Analyze the current stadium conditions:\n"
                    "- Telemetry & Crowd Conditions: {telemetry}\n"
                    "- Active Incidents: {incidents}\n"
                    "- Operational State: {operational_state}\n\n"
                    "Based on these conditions, generate human-readable logistical, routing, safety, and volunteer allocation recommendations.\n"
                    "For every recommendation, you must:\n"
                    "1. Explain what needs to be done clearly.\n"
                    "2. Prioritize it appropriate to the situation ('low', 'medium', 'high', 'critical').\n"
                    "3. Estimate the operational impact and recovery time.\n"
                    "4. Generate a concise operational reasoning referencing specific telemetry bounds, active incidents, or state elements.\n"
                    "Format your response to match the requested schema.\n"
                )
            )
        ]
        super().__init__(metadata, versions)


class AIRecommendationGenerator:
    """AI Agent responsible for generating dynamic stadium recommendations."""

    def __init__(self, orchestrator: AIOrchestrator) -> None:
        self.orchestrator = orchestrator
        self.prompt_definition = AIRecommendationGeneratorPrompt()

        # Register prompt template in the registry
        latest_version = self.prompt_definition.get_version("latest")
        self.orchestrator.registry.register(
            name=self.prompt_definition.metadata.name,
            version=latest_version.version,
            template=latest_version.template,
            description=latest_version.description,
        )

    async def generate_recommendations(
        self,
        telemetry: dict[str, Any],
        incidents: list[dict[str, Any]],
        operational_state: dict[str, Any],
    ) -> AIRecommendationGeneratorResponse:
        """Calls the AI Orchestrator to generate structured recommendations using Gemini."""
        return await self.orchestrator.execute(
            prompt_name=self.prompt_definition.metadata.name,
            prompt_version="latest",
            context_zone_id=None,
            schema=AIRecommendationGeneratorResponse,
            telemetry=json.dumps(telemetry, default=str),
            incidents=json.dumps(incidents, default=str),
            operational_state=json.dumps(operational_state, default=str),
            min_confidence=0.0,
        )
