from typing import List
from pydantic import BaseModel, Field
from app.intelligence.structured_output import AIResponse

class ChatMessageDTO(BaseModel):
    """Represents a single chat message in the conversation history."""
    role: str = Field(..., description="The role of the sender: 'user' or 'assistant'.")
    text: str = Field(..., description="The text content of the message.")

class CopilotChatRequest(BaseModel):
    """Payload representing a request to chat with the ATLAS Copilot."""
    message: str = Field(..., description="The latest query or message submitted by the operator.")
    history: List[ChatMessageDTO] = Field(default_factory=list, description="Ordered conversation log history.")
    language: str = Field("English", description="Target response language.")
    current_page: str | None = Field(None, description="The page the operator is currently viewing.")

class CopilotChatResponse(AIResponse):
    """Structured response detailing the Copilot's response, model parameters, and context citation anchors."""
    text: str = Field(..., description="Markdown response text generated by the copilot assistant.")
    citations: List[str] = Field(..., description="List of exact live references, incidents, or zones cited in the text.")
    confidence_score: float = Field(..., description="Model response confidence rating (0.0 to 1.0).")
    model_version: str = Field(..., description="Model identifier used to fulfill request.")
    execution_time_ms: int = Field(..., description="Orchestration latency duration in milliseconds.")
